org.gradle.jvmargs = -Xmx4096M
org.gradle.parallel = true
unityStreamingAssets = 
unityTemplateVersion=15
unityProjectPath=D:/SIH/sample/uaal-example-master/UnityProject
unity.projectPath=D:/SIH/sample/uaal-example-master/UnityProject
unity.debugSymbolLevel=none
unity.buildToolsVersion=34.0.0
unity.minSdkVersion=23
unity.targetSdkVersion=34
unity.compileSdkVersion=34
unity.applicationId=com.DefaultCompany.UaaLExample
unity.abiFilters=armeabi-v7a,arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.DefaultCompany.UaaLExample
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.0b16/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.0b16/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=23.1.7779620
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.0b16/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
android.useAndroidX=true
android.enableJetifier=true
org.gradle.welcome=never
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
